version: "3.7"
services:
    # imagem micro 01
    elo:
        build:
            args:
                user: admin
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - eloservices
        links:
            - db-elo

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 9090:80
            - 443:443
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - eloservices

    # mysql micro 01
    db-elo:
        container_name: db-elo
        image: mysql:8.0
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - 3312:3306
        command: mysqld --character-set-server=utf8mb4
                --collation-server=utf8mb4_unicode_ci
                --default-authentication-plugin=mysql_native_password --sql-mode=""
        networks:
            - eloservices

    # queue micro 01
    # queue:
    #     build:
    #         args:
    #             user: admin
    #             uid: 1000
    #         context: ./
    #         dockerfile: Dockerfile
    #     restart: unless-stopped
    #     command: "php artisan queue:work"
    #     volumes:
    #         - ./:/var/www
    #     depends_on:
    #         - redis
    #     networks:
    #         - eloservices

    # #redis
    # redis:
    #     image: redis:latest
    #     networks:
    #         - eloservices

networks:
    eloservices:
        driver: bridge
