version: '3.8'

services:
    # microservices
    micro_01:
        build:
            args:
                user: matheus
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        # restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - microservices

    # nginx
    nginx:
        image: nginx:alpine
        # restart: unless-stopped
        ports:
            - 8000:80
            - 443:443
        volumes:
          - ./:/var/www
          - ./docker/nginx/:/etc/nginx/conf.d
        networks:
          - microservices

    # mysql micro 01
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - 3306:3306
        # restart: unless-stooped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_HOST: ${DB_HOST}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        networks:
            - microservices

networks:
    microservices:
        driver: bridge

